export const SheetActions = {
    GET_SHEETS: "GET_SHHETS",
    GET_SHEET_DETAIL: "GET_SHHET_DETAIL",
    CREATE_SHEET: "CREATE_SHEET",
    DELETE_SHEET: "DELETE_SHEET",
    UPDATE_SHEET_INFO: "UPDATE_SHEET_INFO",
    SET_IS_IN_SHEET: "SET_IS_IN_SHEET",
    RESIZE_SHEET: "RESIZE_SHEET",
    UPDATE_SHEET_CELL: "UPDATE_SHEET_CELL"
};

export const ErrorActions = {
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERROR"
};

export const AuthActions = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    AUTH_ERROR: "AUTH_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
};