export const SheetActions = {
    GET_SHEETS: "GET_SHHETS",
    GET_SHEET_DETAIL: "GET_SHEET_DETAIL",
    CREATE_SHEET: "CREATE_SHEET",
    DELETE_SHEET: "DELETE_SHEET",
    UPDATE_SHEET_INFO: "UPDATE_SHEET_INFO",
    SET_IS_IN_SHEET: "SET_IS_IN_SHEET",
};

export const DisplayAction = {
    SET_DISPLAY_DATA: "SET_DISPLAY_DATA",
};

export const TableActions = {
    RESIZE_TABLE: "RESIZE_SHEET",
    UPDATE_TABLE_CELL: "UPDATE_TABLE_CELL"
}

export const BorderActions = {
    RESIZE_BORDER: "RESIZE_BORDER",
    MAKE_BORDER_RESIZED_FALSE: "MAKE_BORDER_RESIZED_FALSE"
};

export const FocusActions = {
    SET_FOCUSED_TABLE_CELLS: "SET_FOCUSED_TABLE_CELLS",
    SET_FOCUS_RECT_DATA: "SET_FOCUS_RECT_DATA"
};

export const ErrorActions = {
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERROR"
};

export const AuthActions = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    AUTH_ERROR: "AUTH_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
};